### ISSUE TITLE
FMod Extension: [macOS] Lots of Feather errors and a non-functioning demo (when run on an x64 Mac)

### ISSUE THREAD

**Issue by peardox** [YoYoGames/GMEXT-FMOD#15] opened 2024-11-13 11:51 UTC
### Which Extension are you reporting this issue for?

FMOD

### Description

The FMod extension demo app builds to broken functionality.
Click on, for example, the Play Stream button and you'll be greeted with a nice big "undefined" string being shown on screen where the Windows version shows the buffer information when streaming

It is notable that https://github.com/YoYoGames/GMEXT-FMOD/issues/16 exists also

This makes me wonder if the two above issues are linked?

### Expected Change

The demo should function the same on all platforms

### Steps To Reproduce

Build and run FMod Extension demo on MacOS

Note that I built the MacOS version both from a Windows host and on an old x64 Mac (IOS test just completed via Windows)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment] 2024-11-14 10:09
Hi @peardox,

Thank you for bringing this issue to our attention. We strive to ensure that our tools and extensions provide consistent functionality across all platforms, and your feedback is essential in helping us achieve that goal.

To better understand and resolve the problem you described, we need a bit more information:

**Extension Version:** Could you please confirm the specific version of the FMOD extension you are using? This will help us identify if this issue is related to a known version or if further investigation is required.

**FMOD SDK Version:** Could you let us know the FMOD SDK version you have integrated with the extension? Different SDK versions might have nuances that could influence functionality.

We understand your frustration, but providing these details will allow us to pinpoint the root cause of the issue and address it effectively. Your input is invaluable in improving the experience for all users, and we appreciate your patience as we work toward a resolution.

Looking forward to your response.

Best regards,

Francisco Dias

**Comment by peardox** [comment] 2024-11-14 10:22
FMod Extension 0.0.9 via github
FMod SDK 2.02

Running on MacBook Pro Late 2013 x64 i7 with MacOS 14 Sonoma (via OpenCore Legacy Patcher)
Also...
Remote compiled on Win11 Host with FMod SDK copied to Windows drive

Both fail in the same way

**Comment by peardox** [comment] 2024-11-14 11:31
It occurred to me that my crappy old x64 Mac was doing something different so I rented a M1 (Scaleway - £2.50 for as day)
The M1 worked fine so this may be an x64 issue

I am buying a new M4 Mac Mini but that's not til Xmas...

Different but allied matter - ios was also having problems built on x64 so going to do a build on my M1-for-a-day

**Comment by DiasFranciscoA** [comment] 2024-11-14 11:39
On another note @peardox,

This issue (https://github.com/YoYoGames/GMEXT-FMOD/issues/16) was a split from this one so we'll mention it here since we cannot tag you from the other issue. Please answer in the issue so we can start tagging you for future information. What terrible problems are you facing when streaming? What kind of errors are you experiencing what can we do to reproduce this? Make sure that your phone has internet connection and that the device is not silenced.. since this will block the stream from happening (this is not a problem with the extension that's is just how iOS works)

**Comment by peardox** [comment] 2024-11-14 11:45
It's actually an iPad Pro (1st gen) over WiFi I'm testing on

Trying a build on the M1 so I can TestFlight it to myself - possibly an x64 build issue (which this will decide)

I've built the demo on the M1 (which has no sound... it's in France) but the demo appeared to function properly. I should be able to grab a FatBinary from there and test it locally (I hope)

**Comment by peardox** [comment] 2024-11-14 12:19
x64 = XCode 16.1
M1-for-a-day = XCoade 15.4 (odd it didn't get newer)

**Comment by peardox** [comment] 2024-11-14 13:47
Well, just sent myself s testflight from Paris and it dies big time on my rubbish old Mac while seems to function fine on an M1 with 8Gb 100s of miles away

May as well try IOS now

**Comment by peardox** [comment] 2024-11-14 14:48
IOS build error via Macs (both of them)

/Users/m1/GameMakerProjects/fmodtestios/extensions/FMOD/pre_build_step.sh 
[FMOD] INIT: Script initialization succeeded (v0.0.9 :: 1).
[FMOD] ERROR: Path '/%YYprojectDir%/%IOS_SDK_PATH%' does not exist or is not accessible.

And, yeah, they both have the IOS SDK

**Comment by DiasFranciscoA** [comment] 2024-11-14 15:16
Thank you again for the feedback, we could reproduce the issue wth the build scripts when building from macOS to iOS, the FMOD extension just got an update (0.0.10) to solve this issue.

**Comment by peardox** [comment] 2024-11-14 20:16
Thanks, Got the M1 for another 12+ hours so can try both

**Comment by peardox** [comment] 2024-11-14 20:49
Oh Yeah, another related ticket - apparently tvOS _should_ be supportable as it's just a subset of the IOS stuff but that don't build either.

This one I believe is just a missing bit of config in the GM extension

**Comment by peardox** [comment] 2024-11-15 00:33
Right, after some delving thru code the issue is that it's trying to link a device lib to a simulator lib
This could be overcome by linking to the correct lib depending on device / simulator

Then there's a bigger problem. You can only build for a physical device if one is attached to the Mac. There is no way to fake a real device in GM (even though XCode is quite happy to do so). GM really needs an equivalent of Any IOS Device (I feel another feasture req coming here)

Without such a fake device there's no way to build for IOS without a real device - which there should be, especially for testflight deployment

**Comment by peardox** [comment] 2024-11-15 01:05
OK, worked out how to fake an IPad in France but now there are a load of missing symbol errors from the extension

Sorry - full log needed for this one - go to the bottom to see the issues

[ipad.fake.log](https://github.com/user-attachments/files/17760041/ipad.fake.log)

**Comment by DiasFranciscoA** [comment] 2024-11-15 10:25
Hi again @peardox,

> Nahh, 0.0.10 also fails
> 
> Here's the end of a very long log (the missing bit is fine)
> 
> [fmod.ios.log](https://github.com/user-attachments/files/17758083/fmod.ios.log)

it actually is working fine now, it's not getting stuck in the same place as before everything is being copied and working fine in the build system. After reviewing your issue, we would like to clarify that **the current FMOD Extension does not support simulators or tvOS**. As such, this would not be classified as a bug but rather as a feature request.

If you require support for tvOS or simulators, we encourage you to submit a **feature request**. This will allow us to consider and plan the inclusion of these features in future updates to the extension.

I will be closing the issue and opening 2 feature request that you can use to track the process of implementation.

We appreciate your understanding and look forward to any additional feedback or feature requests you may have.

Best regards,
Francisco Dias

**Closed by DiasFranciscoA** 2024-11-15 10:25 UTC
Labels: extension-bug

**Comment by peardox** [comment] 2024-11-15 14:30
Did you try building on MacOS as that still can't find

[FMOD] ERROR: Failed to copy '/Users/simon/GameMakerProjects/fmodtestios/api/core/lib/libfmodL.dylib' does not exist or is not accessible.

**Comment by peardox** [comment] 2024-11-15 16:09
![Image](https://github.com/user-attachments/assets/21f6ddd1-c39a-4519-9fe2-0edb6b7a0774)

**Comment by peardox** [comment] 2024-11-15 16:23
Different fault - undefined symbols

![Image](https://github.com/user-attachments/assets/12afa43c-af92-4987-9759-381d7cc46ca7)

**Comment by peardox** [comment] 2024-11-15 16:48
The above only happens on a Mac

Building from Windows is OK
